name: Deploy after Build

on:
  workflow_run:
    workflow: ["To check os distribustion version"]
    types:
      - completed

jobs:
  deploy:
    if: ${{github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Deploying after successful build"
